version: "3"
services: 
  # atom_db:
  #   env_file: .env
  #   container_name: atom-database
  #   restart: on-failure
  #   image: postgres:13.2
  #   volumes: 
  #     - backend-data:/var/lib/postgresql/data
  #   expose: 
  #     - "5432"
  redis:
    container_name: redis
    restart: on-failure
    image: redis
    expose: 
      - "6379"
  # atom_backend:
  #   container_name: atom-backend
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - .:/atom
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment: 
  #     - DB_HOST=atom_db
  #   command: >
  #     sh -c "python manage.py migrate &&
  #            python manage.py runserver 0.0.0.0:8000"
  #   ports: 
  #     - 8000:8000
  #   depends_on:
  #     - atom_db
  #     - atom_redis
  rabbit:
    container_name: rabbitmq
    restart: on-failure
    image: rabbitmq:3.8.16
    env_file: 
      - .env
    ports: 
      - "5672:5672"
  # affinity_celery:
  #   container_name: celery-worker
  #   restart: on-failure
  #   env_file: .env
  #   environment: 
  #     - DB_HOST=atom_db
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: "celery -A atom worker --loglevel=INFO --purge"
  #   depends_on:
  #     - atom_redis
  #     - atom_rabbit
  #     - atom_backend
  #     - atom_db
  # atom_beat:
  #   container_name: celery-beat
  #   restart: on-failure
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: "celery -A atom beat --loglevel=INFO"
    # links: 
    #   - atom_redis
    # depends_on: 
    #   - atom_redis
    #   - atom_rabbit
volumes:
  backend-data:
  # backend-app:
