# Generated by Django 2.2 on 2022-06-01 17:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('_entry', jsonfield.fields.JSONField(default={})),
                ('exit_time', models.DateTimeField(blank=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('pl_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
