# Generated by Django 2.2 on 2022-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20220602_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exit_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
