# Generated by Django 2.2 on 2022-06-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20220602_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
