# Generated by Django 2.2 on 2022-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_order_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tradeId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pl_status',
            field=models.CharField(blank=True, choices=[('TG', 'TGP'), ('CANCELLED', 'CANCELLED'), ('SLPR', 'SLPR'), ('SL', 'SL')], max_length=10, null=True),
        ),
    ]
